apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scaligator-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]